create or replace view VER_ACCOUNT as
SELECT AC.ACCOUNT_ID AS ID,
      AC.ACCOUNT_RAIZ||AC.ACCOUNT_NUMBER AS "NUMBER",
      AC.ACCOUNT_RAIZ AS RAIZ,
      AC.ACCOUNT_DESC AS "DESCRISION",
      AC.ACCOUNT_LEVEL AS "LEVEL",
      AC.ACCOUNT_CREDITO AS CREDITO,
      AC.ACCOUNT_DEBITO AS DEBITO,
      AC.ACCOUNT_DEBITO - AC.ACCOUNT_CREDITO AS SALDO,
      AC.ACCOUNT_STATE AS STATE,
      CASE
         WHEN AC.ACCOUNT_STATE = 1 THEN 'Movimentavel'
         WHEN AC.ACCOUNT_STATE = 2 THEN 'Não Movimentavel'
         ELSE 'Fechada'
      END AS "STATE OBS",
      AC.ACCOUNT_YEAR AS YEAR,
      TO_CHAR(AC.ACCOUNT_DTREG, 'DD-MM-YYYY') AS REGISTRO,
      CASE
        WHEN SUBSTR(AC.ACCOUNT_RAIZ||AC.ACCOUNT_NUMBER, 1, 1) BETWEEN '1' AND '5' THEN 'Resultado'
        WHEN SUBSTR(AC.ACCOUNT_RAIZ||AC.ACCOUNT_NUMBER, 1, 1) BETWEEN '6' AND '8' THEN 'Balanço'
        ELSE 'NA'
      END AS TYPE
   FROM T_ACCOUNT AC
      -- INNER JOIN T_ACCOUNT ACR ON AC.ACCOUNT_ACCOUNT_ID = ACR.ACCOUNT_ID
   ORDER BY "NUMBER" ASC
