create view VER_OPERACAO_PAGAMENTO_REL as
SELECT IPA.IPAY_ID AS "ID",
         PAY.PAY_COD AS "CODIGO",
         'P' AS "OP",
         'Pagamento' AS "OPERACAO",
         MP.MPAY_DESC AS "TIPO",
         TRIM(OT.OBJT_DESC||' '||PAY.PAY_DOCMENTPAYMENT) AS "NUMERO DOCUMENTO",
         AC.COD AS "CONTA",
         TO_CHAR(PAY.PAY_DTPAY, 'DD-MM-YYYY') AS "DATA",
         TM.TMOV_OPERACTION AS "MOVIMENTACAO", 
         PACK_LIB.MONEY(IPA.IPAY_VALUE) AS "VALOR",
         IPA.IPAY_DESC AS "DESCRICAO",
         US.NOME AS "COLABORADOR",
         TO_CHAR(PAY.PAY_DTREG, 'DD-MM-YYYY') AS "REGISTRO",
         PAY.PAY_DTPAY AS "DT_DATA",
         PAY.PAY_DTREG AS "DTREG"
         
     FROM T_PAYMENT PAY
        INNER JOIN T_MODPAYMENT MP ON PAY.PAY_MPAY_ID = MP.MPAY_ID
        INNER JOIN T_OBJECTYPE OT ON PAY.PAY_OBJ_FORMAPAYMENT = OT.OBJT_ID
        INNER JOIN VER_USER US ON PAY.PAY_USER_ID = US.ID_USER
        INNER JOIN T_ITEMPAYMENT IPA ON PAY.PAY_ID = IPA.IPAY_PAY_ID 
        INNER JOIN VER_ALL_ACCOUNT AC ON IPA.IPAY_ACCOUNT_ID = AC.ID
        INNER JOIN T_TYPEMOVIMENTO TM ON IPA.IPAY_TMOV_ID = TM.TMOV_ID
