create view VER_PAGAMENTO_ITEMS as
SELECT
     pay.PAY_ID AS "PAGAMENTO",
     pay.PAY_COD AS "COD PAGAMENTO",
     FORMA_PAY.OBJT_DESC AS "FORMA PAGAMENTO",
     pay.PAY_DOCMENTPAYMENT AS "DOC FORMA PAGAMENTO",
     IPAY.IPAY_BENEFICIARIO AS "BENEFICIARIO",
     IPAY.IPAY_DESC AS "DESCRICAO PAGAMENTO",
     IPAY.IPAY_VALUE AS "VALOR PAGAMENTO",
     IPAY.IPAY_QUANTITY AS "QUANTIDADE",
     AC.COUNT_NIB AS "NUMERO DA CONTA BANCO",
     ACPAY.COUNT_DESC AS "TITULO CONTA PAGAMENTO",
     MD.MOE_NOME AS "MOEDA",
     MD.MOE_SIGLA AS "SIGLA",
     BK.BK_SIGLA||' '||MD.MOE_SIGLA||' '||TIPO_CONTA_BANK.OBJT_DESC AS "DESCRICAO CONTA BANCO",
     IPAY.IPAY_DTREG AS REGISTRO,
     FU.FUNC_CODSEGURADORA AS "USER",
     ACPAY.COUNT_NIB AS "CODIGO CONTA PAGAMENTO"
   FROM T_PAYMENT pay
      INNER JOIN T_ACCOUNT AC ON pay.PAY_ACCOUNT_ID = AC.COUNT_ID
      INNER JOIN T_ITEMPAYMENT IPAY ON pay.PAY_ID = IPAY.IPAY_PAY_ID
      INNER JOIN T_ACCOUNT ACPAY ON IPAY.IPAY_ACCOUNT_ID = ACPAY.COUNT_ID
      INNER JOIN T_FUNCIONARIO FU ON IPAY.IPAY_USER_ID = FU.FUNC_ID
      LEFT JOIN T_BANK BK ON AC.COUNT_BK_ID = BK.BK_ID
      LEFT JOIN T_MOEDA MD ON AC.COUNT_MOE_ID = MD.MOE_ID
      LEFT JOIN T_OBJECTYPE FORMA_PAY ON pay.PAY_OBJ_FORMAPAYMENT  = FORMA_PAY.OBJT_ID
      LEFT JOIN T_OBJECTYPE TIPO_CONTA_BANK ON AC.COUNT_OBJT_SUBTPCOUNT = TIPO_CONTA_BANK.OBJT_ID
