create or REPLACE view VER_CHEQUE as
SELECT CH.CHEQUE_ID AS "ID",
       /*AC."DESC"*/ ac."NUMBER"  AS "CONTA",
       /*AC.NAME*/ac."NUMBER"  AS "CODIGO",
       /*AC.COD*/ac."NUMBER" AS "NIB",
       CH.CHEQUE_SEQINICIO AS "SEQUENCIA INICIO",
       CH.CHEQUE_SEQFIM AS "SEQUENCIA FIM",
       CH.CHEQUE_TTCHEQUE AS "TOTAL CHEQUES",
       CH.CHEQUE_TTDESTRIBUIDO AS "DESTRIBUIDO",
       CASE 
          WHEN CH.CHEQUE_STATE = 1 THEN 'Ativo'
          ELSE 'Fechado'
       END AS  "ESTADO",
       CH.CHEQUE_STATE AS STATE,
       TO_CHAR(CH.CHEQUE_DTREG, 'YYYY-MM-DD') AS "REGISTRO",
       TO_CHAR(CH.CHEQUE_DTFIM, 'YYYY-MM-DD') AS "FIM",
       US.ACCESSNAME AS "COLABORADOR"
   FROM T_CHEQUE CH
      INNER JOIN VER_ACCOUNT AC ON CH.CHEQUE_ACCOUNT_ID = AC.ID
      INNER JOIN VER_USER US ON CH.CHEQUE_USER_ID = US.ID_USER
   WHERE CH.CHEQUE_SEQINICIO  != '-1' 
      OR CH.CHEQUE_SEQINICIO !=  '-1'
   ORDER BY CH.CHEQUE_STATE DESC, CH.CHEQUE_DTREG DESC
