create view VER_OPERACAO_LANCAMENTO_REL as
SELECT LC.LANCACOUNT_ID AS "ID",
       CAST(L.LANCA_ID AS VARCHAR(10)) AS "CODIGO",
       'L' AS "OP",
       'Lancamento' AS "Operacao",
       TP.TLANCA_DESC AS "TIPO",
       LC.LANCACOUNT_DOCNUM AS "MUMERO DOCUMENTO",
       AC.COD AS "CONTA",
       TO_CHAR(LC.LANCACOUNT_DOCDATA, 'DD-MM-YYYY') AS "DATA",
       TM.TMOV_OPERACTION AS "MOVIMENTACAO",
       PACK_LIB.MONEY(LC.LANCACOUNT_VALUE) AS "VALOR",
       LC.LANCACOUNT_MOVDESC AS "DESCRICAO",
       US.NOME AS "COLABORADOR",
       TO_CHAR(L.LANCA_DTREG, 'DD-MM-YYYY') AS "REGISTRO",
       L.LANCA_DATA AS "DT_DATA",
       L.LANCA_DTREG AS "DTREG"
       
   FROM T_LANCAMENTO L
      INNER JOIN VER_USER US ON L.LANCA_USER_ID = US.ID_USER 
      INNER JOIN T_LANCAMENTOACCOUNT LC ON L.LANCA_ID = LC.LANCACOUNT_LANCA_ID
      INNER JOIN VER_ALL_ACCOUNT AC ON LC.LANCACOUNT_ACCOUNT_ID = AC.ID
      INNER JOIN T_TYPEMOVIMENTO TM ON LC.LANCACOUNT_TMOV_ID = TM.TMOV_ID
      INNER JOIN T_TYPELANCAMENTO TP ON L.LANCA_TLANCA_ID = TP.TLANCA_ID
