create OR REPLACE  FUNCTION "FUNC_REG_CONTAFUNCIONARIO"
(
    USER_ID NUMBER,
    ID_FUNCIONARIO NUMBER,
    ID_BANCO NUMBER,
    NIB VARCHAR2
)
RETURN VARCHAR2
IS
    TT NUMBER;
  
  
BEGIN

    UPDATE T_LINHAFUNCIONARIO L
      SET L.LFUNC_ACCOUNTNUMBER = NIB,
          L.LFUNC_BANK_ID = ID_BANCO
       WHERE L.LFUNC_FUNC_ID = ID_FUNCIONARIO
         AND L.LFUNC_STATE = 1;

    RETURN 'true';                              
    
END;