create OR REPLACE view VER_CONTA_MOVIMENTO_RECEBIMENT as
SELECT AM.AMORT_ID AS "ID",
       -- 'R/N '||am.AMORT_ID AS "CODIGO",
       AM.AMORT_DOCUMENTO "DOCUMENTO",
       AM.AMORT_VALOR AS "VALOR",
       
       /*TAX.TX_VENDA * */ AM.AMORT_VALOR AS "VALOR STD",
       'Debito' AS "MOVIMENTO",
       AC."NUMBER" AS "CONTA",
       AM.AMORT_DESC AS "OBSERVACAO",
       TO_CHAR(AM.AMORT_DTREG, 'DD-MM-YYYY') AS "DATA",
       TO_CHAR(AM.AMORT_DTREG, 'DD-MM-YYYY') AS "REGISTRO",
       FU.FUNC_NOME AS "COLABORADOR",
       'Recebimento' AS "OPERACAO",
       
       'R' AS "OP",
       1 AS "TP MOV",
       AM.AMORT_ACCOUNT_ID AS "ID CONTA",
       AM.AMORT_DTREG AS "DATA_SF",
       AM.AMORT_DTREG AS "REGISTRO_SF",
       AM.AMORT_PREST_ID AS "ID PRESTACAO",
       PR.PREST_CTT_ID AS "ID CONTRATO",
       
       AM.AMORT_VALOR  AS "DEBITO",
        0 AS "CREDITO",
        
        MD.MOE_SIGLA AS "MOEDA",
        MD.MOE_ID AS "ID MOEDA"

   FROM T_AMORTIZACAO AM
      INNER JOIN T_FUNCIONARIO FU ON AM.AMORT_USER_ID = FU.FUNC_ID
      INNER JOIN VER_ACCOUNT AC ON AM.AMORT_ACCOUNT_ID = AC.ID
      INNER JOIN T_PRESTACAO PR ON AM.AMORT_PREST_ID  = PR.PREST_ID
      INNER JOIN T_CONTRATO CT ON PR.PREST_CTT_ID = CT.CTT_ID
      INNER JOIN T_MOEDA MD ON CT.CTT_MOE_ID = MD.MOE_ID
      -- INNER JOIN TABLE(PACK_CONTA.GETTAXADAY(CT.CTT_DTREG, MD.MOE_ID)) TAX ON MD.MOE_ID = TAX.TX_MOE_ID
