create OR REPLACE view VER_CONTA_MOVIMENTO as
SELECT CMOV."DATA",CMOV."ID",CMOV."DOCUMENTO",CMOV."VALOR",CMOV."MOVIMENTACAO",CMOV."CONTA",CMOV."REGISTRO",CMOV."OP",CMOV."TP MOV",CMOV."ID CONTA",CMOV."DATA_SF",CMOV."REGISTRO_SF",CMOV."OPERACAO",
       CASE
          WHEN CMOV."TP MOV" = 1 THEN CMOV."VALOR"
          ELSE 0 
       END AS "DEBITO",
       
       CASE
          WHEN CMOV."TP MOV" = 2 THEN CMOV."VALOR"
          ELSE 0 
       END AS "CREDITO"
       ,CMOV."OBSERVACAO"
   FROM VER_CONTA_MOVIMENTO_ALL CMOV
