create or REPLACE  view VER_CONTA_MOVIMENTO_PAGAMENTO as
SELECT ITEM.IPAY_ID AS "ID",
         ITEM.IPAY_NUNDOCUMENT AS "DOCUMENTO",
         ITEM.IPAY_VALUE AS "VALOR",
         /*TAX.TX_VENDA * */ ITEM.IPAY_VALUE AS "VALOR STD",
         TMOV.TMOV_OPERACTION AS "MOVIMENTO",
         AC."NUMBER" AS "CONTA",
         ITEM.IPAY_DESC AS "OBSERVACAO",
         TO_CHAR(PAY.PAY_DTPAY, 'DD-MM-YYYY') AS "DATA",
         TO_CHAR(ITEM.IPAY_DTREG, 'DD-MM-YYYY') AS "REGISTRO",
         FU.FUNC_NOME AS "COLABORADOR",
         'Pagamento' AS "OPERACAO",
         'P' AS "OP",
         ITEM.IPAY_TMOV_ID AS "TP MOV",
         ITEM.IPAY_ACCOUNT_ID AS "ID CONTA",
         PAY.PAY_DTPAY AS "DATA_SF",
         ITEM.IPAY_DTREG AS "REGISTRO_SF",
         ITEM.IPAY_PAY_ID AS "ID PAGAMENTO",
         
         CASE
            WHEN TMOV.TMOV_ID = 1 THEN ITEM.IPAY_VALUE 
            ELSE 0 
         END AS "DEBITO",
         
         CASE
            WHEN TMOV.TMOV_ID = 2 THEN ITEM.IPAY_VALUE 
            ELSE 0 
         END AS "CREDITO",
         'SIGLA'/*MD.MOE_SIGLA*/ AS "MOEDA",
         NULL /*MD.MOE_ID*/ AS "ID MOEDA"
  
     FROM T_ITEMPAYMENT ITEM
        INNER JOIN T_TYPEMOVIMENTO TMOV ON ITEM.IPAY_TMOV_ID = TMOV.TMOV_ID
        INNER JOIN VER_ACCOUNT AC ON ITEM.IPAY_ACCOUNT_ID = AC.ID
        INNER JOIN T_PAYMENT PAY ON ITEM.IPAY_PAY_ID = PAY.PAY_ID
        INNER JOIN VER_ACCOUNT PAYAC ON PAY.PAY_ACCOUNT_ID = PAYAC.ID
        -- INNER JOIN T_MOEDA MD ON PAYAC.COUNT_MOE_ID = MD.MOE_ID
        INNER JOIN T_FUNCIONARIO FU ON ITEM.IPAY_USER_ID = FU.FUNC_ID
        -- INNER JOIN TABLE(PACK_CONTA.GETTAXADAY(ITEM.IPAY_DTREG, MD.MOE_ID)) TAX ON TAX.TX_MOE_ID = MD.MOE_ID
