create trigger TG_POS_REG_ITEMPAYMENT
	after insert or update
	on T_ITEMPAYMENT
	for each row
BEGIN
    -- VISAO DEVEDOR CREDITO IN NICON AS DEBITO IN GERAL | DEBITO IN NICON AS CREDITO IN GERAL
    -- VISAO DEVEDOR CREDITO DIMINUI SALDO  DEBITO AUMENTA SALDO
    IF INSERTING THEN 
    -- IPAY_OPR_ID  {1 - Credito | 2 - Debito}
    -- Depois de registrar a item do pagamento atualizar a conta do pagamento aumentando o seu valor do debito
    
    -- PARA O CREDITO { DIMINUIR O SALDO DA CONTA }
    IF :NEW.IPAY_TMOV_ID = 2 THEN 
        UPDATE T_ACCOUNT APAY
            SET APAY.COUNT_SALDO = APAY.COUNT_SALDO - :NEW.IPAY_VALUEACCOUNT,
                APAY.COUNT_CREDITO = APAY.COUNT_CREDITO + :NEW.IPAY_VALUEACCOUNT
            WHERE APAY.COUNT_ID = :NEW.IPAY_ACCOUNT_ID ;
            
    -- PARA OS DEBITOS { AUMENTAR O SALDO DA CONTA }
    ELSIF :NEW.IPAY_TMOV_ID = 1 THEN
        UPDATE T_ACCOUNT APAY
            SET APAY.COUNT_SALDO = APAY.COUNT_SALDO + :NEW.IPAY_VALUEACCOUNT,
                APAY.COUNT_DEBITO = APAY.COUNT_DEBITO + :NEW.IPAY_VALUEACCOUNT
            WHERE APAY.COUNT_ID = :NEW.IPAY_ACCOUNT_ID ;
    END IF;
        
        
        
    -- Quando for anular os item do pagamento entao repor os valores nas contas dos pagamentos do item
    ELSIF UPDATING AND :NEW.IPAY_STATE = -1 AND :OLD.IPAY_STATE != -1 THEN
       
        -- AO ANULAR A OPERACAO DO CREDIITO { O SALDO DO CREDITO DIMINUI E O SALDO DA CONTA QUE OUTRA HORA DIMINUIU AUMENTA }
       IF :OLD.IPAY_TMOV_ID = 2 THEN -- PARA O CREDITO
         UPDATE T_ACCOUNT APAY
            SET APAY.COUNT_SALDO  = APAY.COUNT_SALDO + :OLD.IPAY_VALUEACCOUNT,
                APAY.COUNT_CREDITO = APAY.COUNT_CREDITO - :OLD.IPAY_VALUEACCOUNT
            WHERE APAY.COUNT_ID = :OLD.IPAY_ACCOUNT_ID;
       
       -- AO ANULAR A OPERACAO DO DEBITO { O SALDO DO DEBITO DIMINUI E O SALDO DA CONTA QUE OUTRA HORA AUMENTOU TABEM DIMINUI}
       ELSIF :OLD.IPAY_TMOV_ID = 1 THEN
         UPDATE T_ACCOUNT APAY
            SET APAY.COUNT_SALDO  = APAY.COUNT_SALDO - :OLD.IPAY_VALUEACCOUNT,
                APAY.COUNT_DEBITO = APAY.COUNT_DEBITO - :OLD.IPAY_VALUEACCOUNT
            WHERE APAY.COUNT_ID = :OLD.IPAY_ACCOUNT_ID;
            
       END IF;
      
    END IF;
END;