create or REPLACE view VER_ACCOUNTBANK as
select ab.ACCOUNTBANK_ID as ID,
    ab.ACCOUNTBANK_NUMBER as "NUMBER",
    b.BK_SIGLA as "BANK",
    m.MOE_SIGLA AS "MOEDA",
    o.OBJT_DESC AS TYPE,
    b.BK_SIGLA||' '||m.MOE_SIGLA||' '||o.OBJT_DESC as "NAME",
    AC.ACCOUNT_RAIZ||AC.ACCOUNT_NUMBER AS "ACCOUNT NUMBER",
    AC.ACCOUNT_DESC AS "ACCOUNT DESC"
  from T_ACCOUNTBANK ab
    INNER JOIN T_BANK b on ab.ACCOUNTBANK_BANK_ID = b.BK_ID
    INNER JOIN T_MOEDA m on ab.ACCOUNTBANK_MOE_ID = m.MOE_ID
    INNER JOIN T_OBJECTYPE o on ab.ACCOUNTBANK_OBJ_TYPEACCOUT = o.OBJT_ID
    INNER JOIN T_ACCOUNTACCOUNTBANK ABC ON ab.ACCOUNTBANK_ID = ABC.AACOUNTBANK_ACCOUNTBANK_ID
    INNER JOIN T_ACCOUNT AC On ABC.AACOUNTBANK_ACCOUNT_ID = AC.ACCOUNT_ID
  WHERE ABC.AACCOUNTBANK_STATE = 1
